server:
  port: 8085
spring:
  mail:
    host: smtp.qq.com
    protocol: smtps
    username: 1009768549@qq.com
    password: twzfblrgzbqjbegf
    port: 465
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///organization?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  web:
    resources:
      static-locations: file:/F:/images/image/,classpath:/static/
logging:
  level:
    com:
      atcx:
        mapper: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml